### ISSUE TITLE
Improve QueryDSL integration

### ISSUE THREAD

**Issue by jexp** [neo4j-contrib/cypher-dsl#10]
Accept QueryDSL types in all sensible places and convert them internally.

**Comment by michael-simons** [comment]
After a bit of investigating I will not continue the effort at the moment. QueryDSL is tight very much to relational and it reads and feels odd to to combine with Cypher. Having it only as provider for compile static information, I would rather consider our own meta model or use some store abstraction like being discussed in Spring Data Commons as static meta model.
