### ISSUE TITLE
Add support for utility functions call

### ISSUE THREAD

**Issue by sergeily** [neo4j-contrib/cypher-dsl#101]
It would be nice to make class FunctionInvocation and interface FunctionDefinition public or add support to call additional functions

For example utility function apoc.create.uuid()
```
MERGE (p:Person {id: apoc.create.uuid()})
SET p.firstName = "Michael", p.surname = "Hunger"
RETURN p
```

**Comment by michael-simons** [comment]
Good point, that is indeed missing and will be included in the next release. For usage see:

https://github.com/neo4j-contrib/cypher-dsl/blob/998af302de14e41925536a05c97810ced065ff2d/neo4j-cypher-dsl/src/test/java/org/neo4j/cypherdsl/core/ProcedureCallsIT.java#L119-L146
