### ISSUE TITLE
NodeProperty names with spaces are not supported

### ISSUE THREAD

**Issue by MiguyM** [neo4j-contrib/cypher-dsl#106]
CypherRenderer generates the following request:
"MATCH (n:`module`) WHERE n.Name = $name RETURN n{.Created By, .Created On, .Last Modified By, .Last Modified On}"
                                                                                                             ^; Error code 'Neo.ClientError.Statement.SyntaxError'

Property names should be delimited with backticks:
"MATCH (n:`module`) WHERE n.Name = $name RETURN n{.&#96;Created By&#96;, .&#96;Created On&#96;, .&#96;Last Modified By&#96;, .&#96;Last Modified On&#96;}"

**Comment by michael-simons** [comment]
Thanks a lot for your report.
