### ISSUE TITLE
Using multiple Conditions.noCondition() in WHERE clause return wrong query

### ISSUE THREAD

**Issue by denisdaniliuk-hqo** [neo4j-contrib/cypher-dsl#112]
Have noticed the same problem like in #110 with WHERE part
Example:
```
Cypher.match(
    nodes.get(SPACE).relationshipTo(nodes.get(TENANT), "OCCUPIED_BY"),
    nodes.get(TENANT).relationshipFrom(nodes.get(COMPANY), "IS_A")
)
.where(
    Conditions.noCondition().or(Conditions.noCondition()) // just simplify condition here but if I receive some UUIDs it will be placed instead of noCondition()
)
.returning(nodes.get(SPACE))
.build();
```
will return query:
```
MATCH (space:`Space`)-[:`OCCUPIED_BY`]->(tenant:`Tenant`), (tenant)<-[:`IS_A`]-(company:`Company`) WHERE  RETURN space
```

**Comment by michael-simons** [comment]
Hey Denis. Thanks again, I was only on mobile when I marked this as duplicate, but no I checked with the test, please compare to the tests added in https://github.com/neo4j-contrib/cypher-dsl/commit/c09e1eda050169e4f189ab49020febe4925a435c and labelled GH-110. This is fixed.

The error was in how it was checked if a condition has actually content or not.
