### ISSUE TITLE
Don't force rendering of aliases when the original object is used.

### ISSUE THREAD

**Issue by K-Lovelace** [neo4j-contrib/cypher-dsl#121]
I'm trying to upgrade from sdn/rx to this project and stumbled upon this:

When generating the following cypher:
```
WITH DISTINCT ltr, u, r, rn, dmn, rn AS nn
WITH DISTINCT ltr, u, nn, r, dmn, rn, CASE WHEN nn:Job THEN 'job' WHEN nn:DiplomaMajor THEN 'diplomaMajor' ELSE 'diploma' END AS type
WITH DISTINCT type, ltr, u, dmn, rn, nn
```
It actually generates this cypher:
```
WITH DISTINCT ltr, u, r, rn, dmn, **rn AS nn**
WITH DISTINCT ltr, u, nn, r, dmn, **nn,** CASE WHEN nn:Job THEN 'job' WHEN nn:DiplomaMajor THEN 'diplomaMajor' ELSE 'diploma' END AS type
WITH DISTINCT type, ltr, u, dmn, **nn, nn**
```
As you can see, once I aliased rn, it only uses the alias name when i try to add nn to the WITH, no matter what method I use.

I am using the 2020.1.6 version, but reproduced it with every 2020.1.X versions.

It happens everytime I alias a variable but I still keep it for the rest of the query.

Am I doing something wrong ?

**Comment by michael-simons** [comment]
Hi Gael. Thanks for opening the issue. Couple of things:

1. Cypher-DSL is not an upgrade from SDN/RX, it has been extracted from it and is now used in https://github.com/spring-projects/spring-data-neo4j to generate queries. It is *100% ok* to be used standalone or in other projects. Also: No Spring dependencies here.
2. Could you please provide me with the Java code you wrote to call the Cypher-DSL so that I can investigate that bug.

**Comment by K-Lovelace** [comment]
Hi Michael, thanks for the response. 

I just moved from the old sdn/rx to spring-data-neo4j and cypher-dsl, that's what I meant by "upgrade".

Unfortunately I would have a hard time extracting the code as it's in a complex cypher generator, but here is the idea:

```
// Somewhere along the way of generating the query...
Node u = node("User").named("u"), rn = node("SomeLabel").named("rn"), ... // same for each variable
Node nn = node("SomeLabel").named("nn");
query = query.withDistinct(ltr, u, r, rn, dmn, rn.as("nn"));
// ... conditions and logic ...
// later in the code
Node rn = anyNode("rn"), nn = anyNode("nn");
query = query.withDistinct(ltr, u, nn, r, dmn, rn, typeCaseExpression);
```

I found a workaround using a custom "RawExpression" that allows me to insert unparsed code in the query:

```
public final class RawExpression extends Literal<CharSequence> implements Condition {
    public RawExpression(CharSequence content) {
        super(content);
    }

    @Override
    public String asString() {
        return String.valueOf(getContent());
    }

}
```
that I use like this: 

```
query = query.withDistinct(ltr, u, r, rn, dmn, new RawExpression("rn as nn"));
```

Is it enough information ? Please let me know.

**Comment by michael-simons** [comment]
Yes, that should help. Thank you!

**Comment by michael-simons** [comment]
See #96 This behavior is pretty much intentional. I try to make both scenarios work.

**Comment by michael-simons** [comment]
This is fixed now and will be out in February.
