### ISSUE TITLE
Add support for index hints.

### ISSUE THREAD

**Issue by K-Lovelace** [neo4j-contrib/cypher-dsl#122]
Is it possible to add support for USING keyword ?

https://neo4j.com/docs/cypher-manual/current/query-tuning/using/#:~:text=A%20planner%20hint%20is%20used,query%20with%20the%20USING%20keyword.

Something like 
```
Cypher.match(node.relationshipTo(otherNode, "HAS")).usingScan(otherNode, "CustomLabel")
```
would be nice.

**Comment by michael-simons** [comment]
Hi Gael. Oh, that's an interesting request, didn't expect that people are going to use the DSL for queries that advanced.

And sure, that's perfectly valid request.

**Comment by K-Lovelace** [comment]
Hi Michael. 

I have a lot more feature requests that I work around for now using the "RawExpression" trick, here is a quick list:

- toFloat function ([](https://neo4j.com/docs/cypher-manual/current/functions/scalar/#functions-tofloat)) and similar
- timestamp() function ([](https://neo4j.com/docs/cypher-manual/current/functions/scalar/#functions-timestamp))
- Apocs methods (I use apoc.map.groupBy, apoc.coll.sum, apoc.map.mergelist, but I believe others would be nice to have to)
- Access to properties on other things than nodes (e.g. `last(collectedThings).name`)
- duration methods ([](https://neo4j.com/docs/cypher-manual/current/functions/temporal/duration/#functions-duration-computing))
- Access to duration, datetime and time properties (years, months, minutes, etc.)

Should I create a different issue for each one of them ?

**Comment by michael-simons** [comment]
* Function for time related things are there: https://github.com/neo4j-contrib/cypher-dsl/blob/main/neo4j-cypher-dsl/src/main/java/org/neo4j/cypherdsl/core/Functions.java#L1144
* APOC specific ones are not gonna happen. You can build them like this https://github.com/neo4j-contrib/cypher-dsl/blob/main/neo4j-cypher-dsl/src/test/java/org/neo4j/cypherdsl/core/CypherIT.java#L3418-L3439
* Properties of expressions: Please create a ticket :)

**Comment by K-Lovelace** [comment]
Yes, I saw the time functions (which are great news by the way!) but I'm missing functions like `duration.between(instant1, instant2)`, or `time().years`. Combine this with properties of expressions and I couldn't be happier!
