### ISSUE TITLE
Expose nested building of nested properties as public API.

### ISSUE THREAD

**Issue by K-Lovelace** [neo4j-contrib/cypher-dsl#123]
I would like to access properties on approximately any expression:

- FunctionInvocations : `datetime().epochseconds`, `last(collectedThings).name`
- Nested objects : `a.b.c`
- Anything when that's possible in Cypher really

Thanks a ton!

**Comment by michael-simons** [comment]
Hey @K-Lovelace 

We have org.neo4j.cypherdsl.core.Cypher#property(org.neo4j.cypherdsl.core.Expression, java.lang.String)

``
public static Property property(Expression expression, String name)
```

Which would work for function invocations:

```
@Test // GH-123
void propertiesOfFunctions() {

	Statement statement = Cypher.returning(Cypher.property(Functions.datetime(), "epochSeconds")).build();
	Assertions.assertThat(cypherRenderer.render(statement))
		.isEqualTo("RETURN datetime().epochSeconds");
}
```

And

```
@Test // GH-123
void propertiesOfFunctionsInsideQuery() {

	Expression collectedThings = Functions.collect(Cypher.name("n")).as("collectedThings");
	Statement statement = Cypher.match(Cypher.anyNode().named("n"))
		.with(collectedThings)
		.returning(Cypher.property(Functions.last(collectedThings), "name")).build();
	Assertions.assertThat(cypherRenderer.render(statement))
		.isEqualTo("MATCH (n) WITH collect(n) AS collectedThings RETURN last(collectedThings).name");
}
```

And we do actually handle nested properties, but this is not yet exposed on `Cypher.property`, which I am gonna change.

"Anything that's possible in Cypher" will take while, though :)

**Comment by K-Lovelace** [comment]
Hi @michael-simons,
This function does meet my needs ! I will wait patiently for the nested properties to remove my ugly workarounds, thanks a lot!

**Comment by michael-simons** [comment]
This is now implemented in the main branch. Feel free to try it out already. You can get the latest build via

```xml
	<dependencies>
		<dependency>
			<groupId>com.github.neo4j-contrib</groupId>
			<artifactId>cypher-dsl</artifactId>
			<version>main-SNAPSHOT</version>
		</dependency>
	</dependencies>

	<repositories>
		<repository>
			<id>jitpack.io</id>
			<url>https://jitpack.io</url>
		</repository>
	</repositories>
```

But you would need to have to exclude the original dependency from Spring Data Neo4j (the original coordinates of the Cypher DSL are `org.neo4j:neo4j-cypher-dsl`.

**Comment by K-Lovelace** [comment]
Hi Michael, thank you, I'll try to have a look at it before the next release. When will these changes be available on the main release of spring-boot-starter-neo4j ?

**Comment by michael-simons** [comment]
Yes, we make sure to release 2021.0.0 in time for the next patch to Spring Data Neo4j.
