### ISSUE TITLE
can this library project relationships?

### ISSUE THREAD

**Issue by arif-hanif** [neo4j-contrib/cypher-dsl#150]
MATCH (`movie`:`Movie`) 
RETURN `movie` { .title , .plot , actors: [(`movie`)<-[:`ACTED_IN`]-(`movie_actors`:`Actor`) | movie_actors { .name }] } AS `movie`

**Comment by arif-hanif** [comment]
found it in the updates https://github.com/neo4j-contrib/cypher-dsl/blob/main/neo4j-cypher-dsl/src/test/java/org/neo4j/cypherdsl/core/CypherIT.java#L3920

**Comment by michael-simons** [comment]
Hey Arif. Thanks for taking your time going to the code. Yes, the docs are in need for completion. 

If you have more questions, please let me know!
