### ISSUE TITLE
Make Relationship and RelationshipChain the same thing ?

### ISSUE THREAD

**Issue by K-Lovelace** [neo4j-contrib/cypher-dsl#152]
Hi,

I've been having issues with the Relationship and RelationshipChain. They behave exactly the same (Exposing relationships, Extending Patternelement...) yet I can't have a method returning a "superclass" of them.

What I would like to do is:

```
public Relationship getRelation() {
    if (condition)
        return node("A").relationshipTo(node("B"));
   else
        return node("A").relationshipTo(node("B")).relationshipTo(node("C"));
}
```

And then use this method in either way:

```
 match(getRelation()).returning(Asterisk.INSTANCE);
```
or
```
match(getRelation().relationshipTo(node("D"))).returning(Asterisk.INSTANCE)
```

Right now, I can either return a PatterElement or a ExposesRelationship (using the raw type), but I really feel the two classes should be the same, no ?

Thank you for your awesome work!

**Comment by K-Lovelace** [comment]
Just found out that RelationshipPattern is what I want for above code, but here is another one that does'nt work:

```
        if (subLTChains) {
            RelationshipChain leadsTo;
            leadsTo = start.relationshipTo(node("Resume"), "PART_OF").length(0, 1)
                .relationshipTo(node("Resume"), "IS_PARALLEL").length(0, 1);

            if (DIRECTION_BACKWARD.equals(direction)) {
                leadsTo = leadsTo.relationshipFrom(end, "LEADS_TO");
            } else {
                leadsTo = leadsTo.relationshipTo(end, "LEADS_TO");
            }
            if (length > 1)
                leadsTo = leadsTo.length(length, length);
            return leadsTo;
        } else {
            Relationship leadsTo;

            if (DIRECTION_BACKWARD.equals(direction)) {
                leadsTo = start.relationshipFrom(end, "LEADS_TO");
            } else {
                leadsTo = start.relationshipTo(end, "LEADS_TO");
            }
            if (length > 1)
                leadsTo = leadsTo.length(length, length);
            return leadsTo;
        }
```

I have to duplicate the code because of length method that is not on RelationshipPattern, so maybe those methods should be declared on this interface ?

**Comment by michael-simons** [comment]
Hi Cael. I have added a tests that demonstrates how to solve this, see:

https://github.com/neo4j-contrib/cypher-dsl/blob/962f3635df3a0c2b6b821d16421f8d1bc6093237/neo4j-cypher-dsl/src/test/java/org/neo4j/cypherdsl/core/IssueRelatedIT.java#L592-L627

While nodes, relationships and chained relationships are all [pattern elements](https://s3.amazonaws.com/artifacts.opencypher.org/railroad/PatternElement.html), relationships and chained relationships are not both relationships. Nodes and relationships can be used as entities AND pattern elements, while chained relationships can not.

I hope this helps.

**Comment by K-Lovelace** [comment]
Thanks for your response, that's what I ended up using.  

If I read your doc correctly, Relationship and RelationshipChain both have RelationshipDetails, e.g. length, max, min, unbounded method could be part of the ExposesRelationship interface ? Or would that make the interface too much ? Even an other interface holding the signatures of those methods would allow me to refactor this code into a nice short code :)
