### ISSUE TITLE
Make startNode and endNode take Named instead of only Relationship

### ISSUE THREAD

**Issue by K-Lovelace** [neo4j-contrib/cypher-dsl#153]
Hi,

I would like to use the startNode and endNode function with Named objects and not just Relationship, as I use them inside pattern comprehension and therefore do not have a Relationship object to use. I see in the code that it only uses "getSymbolicName" method, so any Named node could be used (although it wouldn't work in Cypher). 

Is it possible to add in future release ?  

I wrote my own for the moment:

```
    /**
     * Creates a function invocation for {@code startNode{}}.
     * See <a href="https://neo4j.com/docs/cypher-manual/current/functions/scalar/#functions-startnode">startNode</a>.
     *
     * @param relationship The relationship for which the start node be retrieved
     * @return A function call for {@code startNode()} on a path.
     * @since 2020.0.2
     */
    public static FunctionInvocation startNode(Named relationship) {

        Assertions.notNull(relationship, "The relationship for startNode is required.");
        return FunctionInvocation.create(BuiltInFunctions.Scalars.START_NODE,
            relationship.getSymbolicName()
                .orElseThrow(() -> new IllegalArgumentException("The relationship needs to be named!")));
    }
```

Bonus: there was a typo in the assertions: endNode instead of startNode

**Comment by michael-simons** [comment]
Sure, we have that in a couple of places.

**Comment by michael-simons** [comment]
The method signature should not be changed, but keep as is.
I'm ok with introducing two additional overloads `startNode(SymbolicName s)` and `endNode(SymbolicName s)` respectively. The original methods must than delegate to them.

**Comment by michael-simons** [comment]
I’d rather not extend that api, especially it seems feasible running your custom builder.
