### ISSUE TITLE
Provide a method to turn a Java map into an expression.

### ISSUE THREAD

**Issue by mrksph** [neo4j-contrib/cypher-dsl#157]
I have a Map<String, String> of properties.

I wan't to execute a query to find all Nodes of a given type that matches the properties of the map.

I've tried to iterate the map and then use withProperties in each iteration node.withProperty(key, value)  but it seems to return a Node object with property set to null.

**Comment by michael-simons** [comment]
That would be something like this:

```java
var aMapOfProperties = Map.of("prop1", 23, "theTruth", 42, "somethingElse", "foobar");

		var node = Cypher
			.node("ANode")
			.named("n")
			.withProperties(aMapOfProperties.entrySet().stream()
				.flatMap(e -> Stream.of(e.getKey(), e.getValue() instanceof Expression ? e.getValue() : Cypher.literalOf(e.getValue()))
			).toArray());
```

Renders as `MATCH (n:`ANode` {prop1: 23, somethingElse: 'foobar', theTruth: 42}) RETURN n`. 

But I'm gonna provide a convenience method for it.

**Comment by mrksph** [comment]
Thanks Michael, very fast! I'll let you know when I try it out
