### ISSUE TITLE
SDN 6 @Id-annotated enum field is not added to generated NodeBase property list

### ISSUE THREAD

**Issue by fbiville** [neo4j-contrib/cypher-dsl#177]
Reproduced with Cypher DSL annotation processor version `2021.1.2`.

I have this very simple Spring Data Neo4j entity:

```java
@Node(labels = "Transport")
public class ConnectorTransport {

    @Id
    private final ConnectorTransportType value;
```
where `ConnectorTransportType` is just:
```java
public enum ConnectorTransportType {

    HTTP, BOLT
}
```

The resulting generated `NodeBase` implementation does not list `value` as a property.

After further analysis, it appears that the annotation processor wrongly assumes this field denotes a relationship, because the `Supplier<Boolean>` in `org.neo4j.cypherdsl.codegen.sdn6.SDN6AnnotationProcessor.GroupPropertiesAndRelationships#isAssociation` throws a `ClassNotFoundException` when trying to load the `ConnectorTransportType` class, so:
```java
private boolean isAssociation(Set<Element> declaredAnnotations, VariableElement field) {
    // [...]
    return explicitRelationship || !(isTargetNodeOrComposite || simpleTypeOrCustomWriteTarget.get());
    //     false                || !(false                   || false)
}
```
returns `true`!

**Comment by michael-simons** [comment]
That's a great analysis as always, thank you.

The `enum` is a red herring, though… It appears that I messed up the class loading for inner classes.

**Comment by fbiville** [comment]
I wanted to model a natural primary key with a finite set of values (which translate to a finite set of nodes in the graph), hence the enum. We can discuss offline about better approaches of course :)

Thanks for fixing this!
