### ISSUE TITLE
Investigate parsing Cypher into DSL components.

### ISSUE THREAD

**Issue by michael-simons** [neo4j-contrib/cypher-dsl#181]
Using Neo4j's JavaCC Cypher parser we could parse fragments of Cypher-Strings into DSL components like conditions and attach them to prebuild statements, having a nice combination of base queries that can be enriched via custom fragments.

**Comment by Andy2003** [comment]
Why to just parse fragments and not the whole statement?
A usecase (we got) would be that the user can define a statement to be used as subquery.

**Comment by Andy2003** [comment]
link #185

**Comment by michael-simons** [comment]
Because it's WiP and not my main task ;)

**Comment by michael-simons** [comment]
add hooks to:
- rewrite / add Labels
- rewrite / add Types
