### ISSUE TITLE
Why does the static model do so much instanciation ?

### ISSUE THREAD

**Issue by K-Lovelace** [neo4j-contrib/cypher-dsl#191]
When you do `Division division = Division.DIVISION.named("d").withProperties(...);`
The DIVISION is instanciated once on compilation, but named instanciates a new Division and withProperties re-instanciates another new Division.

Is it by design ? Is there a way to provide a namedWithProperties(String s, Properties properties) method ? We are worried about memory load at runtime.

**Comment by michael-simons** [comment]
The model classes are - much like what they are based on - immutable by design. The references are not kept around, so I would trust the garbage collector to get rid of them sooner than later.
