### ISSUE TITLE
Conditional pattern expressions must not introduce new symbolic names.

### ISSUE THREAD

**Issue by K-Lovelace** [neo4j-contrib/cypher-dsl#192]
We have a big issue with automatically named nodes. Is it possible to turn it down in our project ?

Here is the cypher building:

```
public static Statement objectToPush(String application,
                                         int limit
                                        ) {
        Application app = Application.APPLICATION.named("app");
        User u = User.USER.named("u");
        ModelA r = ModelA.MODEL_A.named("r");
        Node uId = anyNode("u_id");
        RelationshipModel<Application, User> rel = app.relationshipModel(u).named("rel"); // Helper method to keep left to right readbility, takes care of the instantiation 
        return match(app)
            .where(app.PROPERTY_B.isEqualTo(parameter("app", application)))
            .match(rel)
            .where(u.hasLabels("SOME_LABEL"))
            .withDistinct(u.getRequiredSymbolicName(), app.getRequiredSymbolicName(),
                          rel.REL_PROPERTY.as(uId.getRequiredSymbolicName()))
            .limit(limit)
            .match(u.relationshipTo(r, "OTHER_RELATIONSHIP"))
            .where(r.hasLabels("ANOTHER_LABEL").and(app.relationshipModel(r).asCondition().not()))
            .optionalMatch(app.relationshipTo(ModelB.MODEL_B, "SOME_REL")
                               .relationshipTo(ModelB.MODEL_B, "SOME_OTHER_REL").length(0, 1)
                               .relationshipTo(u, "YET_ANOTHER_REL"))
            .returning(astrerisk())
            .build()
    }
```

builds the Cypher (I pointed what is wrong):

```
MATCH (app:Application)
WHERE app.application = $app
MATCH (app)-[rel:RELATIONSHIP_MODEL]->(u:User)
WHERE u:SomeLabel
WITH DISTINCT u, app, rel.rel_property AS u_id LIMIT 1000
MATCH (u)-[:OTHER_RELATIONSHIP]->(r:Resume)
WHERE (r:AnotherLabel AND NOT ((app)-[FxtVkWuw006:RELATIONSHIP_MODEL]->(r))) // EXPECTED: (app)-[:RELATIONSHIP_MODEL]->(r) (Cannot name something in a WHERE!)
OPTIONAL MATCH (app)-[:SOME_REL]->(JoLWSKpR007:Word)-[:SOME_OTHER_REL*0..1]->(JoLWSKpR007)-[:YET_ANOTHER_REL]->(u) // EXPECTED: (:Word)-[:SOME_OTHER_REL*0..1]->(:Word)
RETURN *
```

We may not be using the cypher dsl as intended (in that case please point ou our mistakes), but this is how we felt comfortable writing it.
The two principal problems here are: it shouldn't add a non-existing name in a condition and it shouldn't add a name when using the static meta-model constant.

A quickwin for us would be the possibility to disable this feature (we prefer giving our own names to our variables).

Any intel on that ? Thanks a lot!

**Comment by michael-simons** [comment]
that's definitely a bug. Thanks for spotting it.

**Comment by michael-simons** [comment]
Can you please share your helper method? `app.relationshipModel` ?

**Comment by K-Lovelace** [comment]
```
public @NotNull <T extends AbstractNodeBase<T>> RelationShipModel<Application,T> relationshipModel(T node) {
        return new RelationshipModel<>(this, node);
    }
```

**Comment by michael-simons** [comment]
So I guess what's happening is

- You have of course and rightfully so properties on your relationship model, like `public final Property CREATED_AT = this.property("createdAt");` which I have in the example
- This will trigger the container (a node or a relationship (the later in this case)) to be dereferenced for a symbolic name, which is needed to address the property later. _That should answer your original question_
- The thing has a name than
- The name is rendered when the thing is used first time
- regardless of wether it is used as pattern condition or not _That is the bug_

Can be reproduced by explicitly naming things, too:

```java
	@Test
	void patternExpressionsAreNotAllowedToIntroduceNewVariables() {

		Node bike = Cypher.node("Bike").named("b");
		Node owner = Cypher.node("Owner").named("o");
		Relationship owns = owner.relationshipTo(bike, "OWNS").named("r");

		Statement statement = Cypher.match(bike)
			.where(owns.asCondition())
			.with(bike)
			.returning(bike.property("f"))
			.build();
		assertThat(statement.getCypher()).isEqualTo("MATCH (b:`Bike`) WHERE (:`Owner`)-[:`OWNS`]->(b) WITH b RETURN b.f");
	}
```

I'm gonna fix this :)

**Comment by K-Lovelace** [comment]
So if I get you correctly, in order to use `match(bike.relationshipTo(Owner.OWNER))` and have `MATCH (b:Bike)-->(:Owner)` and not  `MATCH (b:Bike)-->(egzrhge:Owner)`  I have two solutions: Not setting properties final constants in my model or using `node(Owner.$TYPE)` ?

**Comment by michael-simons** [comment]
Yeah… 
The goal with those model methods was that a user should be able to boil out of them anytime. So your best bet before a fix is out is to just create a new relationship (and I think you just wrote that)
