### ISSUE TITLE
Snapshot builds to match neo4j releases?

### ISSUE THREAD

**Issue by cleishm** [neo4j-contrib/cypher-dsl#21]
Hi,

Is it possible to get snapshot builds of cypher-dsl made (and published via maven) whenever a new snapshot of neo4j is released? Likewise for milestone and stable releases of neo4j?

Thanks!
Chris

**Comment by michael-simons** [comment]
Hi @ractive. We are rebooting this project, but we won't provide snapshot builds apart the ones created by our GitHub actions (See for [example this here](https://github.com/neo4j-contrib/cypher-dsl/runs/823030393?check_suite_focus=true)).
