### ISSUE TITLE
Daily SNAPSHOT relase

### ISSUE THREAD

**Issue by TimmyStorms** [neo4j-contrib/cypher-dsl#29]
Is it possible to publish a daily SNAPSHOT build to http://m2.neo4j.org/content/repositories/snapshots/org/neo4j/neo4j-cypher-dsl/?

Other Neo4j modules seem to have this.

Thanks!
Timmy

**Comment by michael-simons** [comment]
Hi @TimmyStorms. We are rebooting this project, but we won't provide snapshot builds apart the ones created by our [GitHub actions](https://github.com/neo4j-contrib/cypher-dsl/runs/823030393?check_suite_focus=true). Thanks.
