### ISSUE TITLE
[Parser] Getting label corresponding to property parsed

### ISSUE THREAD

**Issue by ikwattro** [neo4j-contrib/cypher-dsl#302]
Imagine the following query : 

```
MATCH (n:Person)-[:WORKS_AT]->(c:Company)
REMOVE c.name
```

The parser will return `name` for the property removed, but we don't know if it's on Person or Company.

**Comment by michael-simons** [comment]
I have added an example how to approximately do this with the current API. Maybe it's worth experimenting a bit with that approach.

Re visiting the segments again all over the place: I would rather facilitate the AST we have than exposing internals to get specific attributes.
