### ISSUE TITLE
Release version 2.0.2

### ISSUE THREAD

**Issue by alexpanov** [neo4j-contrib/cypher-dsl#32]
Hi Michael,

Current snapshot of version 2.0.2 add quite a useful feature of using labels. This is something that I want to make use of but in order to do so I have to copy Cypher-DSL to my project with a different version label so that it can be built and installed.
Please release version 2.0.2.

Thank you,
Alex

**Comment by sebbaum** [comment]
Hi @jexp,
when do you plan to release a new version containing recent changes?
I'm looking forward to a new official (maven) release.

Cheers
Sebastian

**Comment by michael-simons** [comment]
Same as the other ones, @jexp
