### ISSUE TITLE
ZonedDateTime custom format

### ISSUE THREAD

**Issue by Hardu2203** [neo4j-contrib/cypher-dsl#389]
I am using the cypher-dsl with AWS Neptune.

At the moment I am getting the following:
`Caused by: org.springframework.dao.NonTransientDataAccessResourceException: "Unexpected server exception 'Unable to parse the date time = 2022-06-19T15:47:38.590917308Z[UTC]'"; Error code '"BoltProtocol.unexpectedException"'; nested exception is org.neo4j.driver.exceptions.DatabaseException: "Unexpected server exception 'Unable to parse the date time = 2022-06-19T15:47:38.590917308Z[UTC]'"
`

The error is thrown because AWS does not support ISO_ZONED_DATE_TIME format for datetime (ZonedDateTime), as specified in  `org.neo4j.cypherdsl.core.TemporalLiteral` class.  [neptune-openCypher-differences](https://docs.aws.amazon.com/neptune/latest/userguide/feature-opencypher-compliance.html#opencypher-compliance-differences).

If I could somehow change `datetime('2022-06-19T15:47:38.590917308Z[UTC]')` to `datetime('2022-06-19T15:47:38')` in my cypher statement it would solve my problem.

Would it be possible to somehow allow for custom datetime formats in the cypher-dsl?

Any advice on how I can possibly achieve this, would be much appreciated. :pray:

**Comment by michael-simons** [comment]
Hello @Hardu2203 

That's a kind of a tricky issue on several levels. Let's start with the one we can solve:

You are using Spring Data Neo4j, right? 

* How are you passing the parameter? 
* Are you passing the parameter to a custom annotated repository method (using `@Query`)
* Or are you passing it to a custom query using Cypher-DSL directly?

In case of the former, one solution is to pass the parameter as formatted string value and recreate it on the server again with Cypher constructs understood by Neptune.

One workaround is to use the following, idk if Neptune supports this

```java
@Test // GH-389
	void shouldRenderCorrectDateTimeCall() {

		Expression datetime = Functions
			.datetime(toMap(ZonedDateTime.parse("2022-06-19T15:47:38.590917308Z[UTC]")));
		assertThat(Cypher.returning(datetime).build().getCypher()).isEqualTo(
			"RETURN datetime({year: 2022, month: 6, day: 19, hour: 15, minute: 47, second: 38, nanosecond: 590917308, timezone: 'UTC'})");
	}

	static MapExpression toMap(ZonedDateTime value) {
		return Cypher.mapOf(
			"year", Cypher.literalOf(value.getYear()),
			"month", Cypher.literalOf(value.getMonthValue()),
			"day", Cypher.literalOf(value.getDayOfMonth()),
			"hour", Cypher.literalOf(value.getHour()),
			"minute", Cypher.literalOf(value.getMinute()),
			"second", Cypher.literalOf(value.getSecond()),
			"nanosecond", Cypher.literalOf(value.getNano()),
			"timezone", Cypher.literalOf(value.getZone().toString())
		);
	}
```

It's a bit tricky for me as a Neo4j employee to things to Cypher DSL to make it tick better with Neptune. 

So in theory, I could add this to the `TemporalLiteral` but the question is: How do you get an instance of that? Through `Cypher.literalOf`? Well, then I need add an overload to the method with a config context.
Or do you pass a value as a literal somewhere down the stack in Spring land? So I need to propagate that.
That would end up in me deciding, I should add this to the dialect support and that would technically be nice, but… you get the point.

When writing this: Are you sure the temporal value needs to be literal? Couldn't it be an actual parameter? 

If you can share some more of your stack, I am sure we can figure this out.

**Comment by Hardu2203** [comment]
Hi @michael-simons .

Thank you for the help, sorry I should have added my stack.

I am using:
- Spring Data Neo4j  
- Generating the static model with `org.neo4j:neo4j-cypher-dsl-codegen-sdn6`
- Extended repository with `CypherdslStatementExecutor`

Thank you, you are right I got into the bad habit of using `literalOf` everywhere. 🤦🏻‍♂️ 

So I got it working with `Cypher.raw`, like this 

```kotlin
    @Test
    fun zonedDateTimeRaw() {

        val formatter: DateTimeFormatter = DateTimeFormatter.ofPattern("yyyy-MM-dd'T'HH:mm:ss")

        val birthDay = ZonedDateTime.now()

        val person = Person_.PERSON.withProperties(
            Person_.PERSON.NAME, literalOf("Hardu"),
            Person_.PERSON.SURNAME, literalOf("Nel"),
            Person_.PERSON.BIRTH_DAY, Cypher.raw("datetime('${formatter.format(birthDay)}')"),
        ).named("person")

        val statement = Cypher.create(person).returning(person).build()

        assertEquals(
            """CREATE (person:`Person` {name: 'Hardu', surname: 'Nel', birthDay: datetime('${formatter.format(birthDay)}')}) RETURN person""",
            statement.cypher
        )

        val savedPerson = personRepository.findOne(statement)

        assertEquals(formatter.format(birthDay), formatter.format(savedPerson.get().birthDay))
    }
```

I could not find an example of where `Cypher.parameter` was used with a `create` clause.  My attempt was...

```kotlin
    @Test
    fun zonedDateTimeParam() {

        val formatter: DateTimeFormatter = DateTimeFormatter.ofPattern("yyyy-MM-dd'T'HH:mm:ss")

        val birthDay = ZonedDateTime.now()

        val person = Person_.PERSON.withProperties(
            Person_.PERSON.NAME, literalOf("Hardu"),
            Person_.PERSON.SURNAME, literalOf("Nel"),
            Person_.PERSON.BIRTH_DAY, Cypher.parameter("birthDay").withValue("datetime('${formatter.format(birthDay)}')"),
        ).named("person")

        val statement = Cypher.create(person).returning(person).build()

        assertEquals(
            "CREATE (person:`Person` {name: 'Hardu', surname: 'Nel', birthDay: \$birthDay}) RETURN person",
            statement.cypher
        )

        val savedPerson = personRepository.findOne(statement)

        assertEquals(formatter.format(birthDay), formatter.format(savedPerson.get().birthDay))
    }
```
I get `org.neo4j.driver.exceptions.DatabaseException: "Unexpected server exception 'MissingParameter'"` exception.

Lastly, should I lean toward using `parameters` and `raw` more in the future?  Is there maybe a performance benefit due to the query execution plan possibly being reused from cache?  Like in [RDB](https://use-the-index-luke.com/sql/where-clause/bind-parameters) 

Thanks again for all the help. 🙌🏻

**Comment by michael-simons** [comment]
Hey @Hardu2203 I haven't added your code into the tests here (Kotlin), but I added my own example (see the attached PR).

That's the gist of it

```java
Optional<Person> createNewPerson(NewPersonCmd newPersonCmd) {
	var p = Person_.PERSON.withProperties(
		Person_.PERSON.NAME, Cypher.anonParameter(newPersonCmd.getName()) // <.>
	).named("p");

	var statement = Cypher.merge(p)
		.onCreate().set(
			p.BORN, Cypher.parameter("arbitraryName")
				.withValue(newPersonCmd.getDob().getYear()), // <.>
			p.DOB, Cypher.anonParameter(newPersonCmd.getDob()) // <.>
		).returning(p).build();
	return peopleRepository.findOne(statement);
}
```

Will be rendered as this

```
[http-nio-auto-1-exec-1] 2022-06-21 11:40:57,732 DEBUG    org.springframework.data.neo4j.cypher: 313 - Executing:
MERGE (p:`Person` {name: $pcdsl01}) ON CREATE SET p.born = $arbitraryName, p.dob = $pcdsl02 RETURN p
[http-nio-auto-1-exec-1] 2022-06-21 11:40:57,735 TRACE    org.springframework.data.neo4j.cypher: 334 - with parameters:
:param arbitraryName => 1990
:param pcdsl01 => 'Liv Lisa Fries'
:param pcdsl02 => 1990-10-31T22:42Z[UTC]
```

Don't let the output of the last parameter irritate you, this is just (SDN) logging with the default format. The parameter will always be used by value, not as literal.

so, this is how you would use the temporal with a parameter and not as literal and actual the best solution for your issue I think. I added the example as docs too, so that others my benefit from it as well.

To your last question: Yes and no. Using parameters will allow the server - well, at least Neo4j, don't know about Neptune - to cache the queries and just fill in the parameters, much like other databases. raw on the other hand is just an escape hatched if you have a query fragment not supported by Cypher-DSL to smuggle in some raw cypher, which will just be inserted into the Cypher-DSL-AST and eventually be rendered to Cypher "as-is"

Good luck and thanks for your feedback here!

**Comment by michael-simons** [comment]
Docs released today: https://github.com/neo4j-contrib/cypher-dsl/releases/tag/2022.5.0
