### ISSUE TITLE
Cannot remove lablels

### ISSUE THREAD

**Issue by wgorder** [neo4j-contrib/cypher-dsl#42]
@jexp 

I found I cannot remove labels.  I see that remove currently only takes reference expressions:

```
    UpdateNext remove(ReferenceExpression... expressions);

    UpdateNext remove(Iterable<ReferenceExpression> expressions);
```

Perhaps the easiest way would be to add two more that take LabelValue s

```
   UpdateNext remove(LabelValue... labelValues);
    UpdateNext remove(Iterable<LabelValue> labelValues);
```

This would works since cypher allows you to have multiple remove clauses.  It is a little icky though in that LabelValue is not an interface but short of adding a new one just for this I don't see a better way.  Do you have an opinion on this?

**Comment by wgorder** [comment]
Alright I am looking at this more, I think it is maybe best to relax the requirement to Expression and just throw an exception when creating the RemoveClause if the Expression type is not valid.

**Comment by jexp** [comment]
Yes, I think so too.

Remove should actually only support Property and Label identifiers.

**Comment by wgorder** [comment]
Alright I have a PR to be reviewed.
