### ISSUE TITLE
collect(distinct(identifier)) requires cast

### ISSUE THREAD

**Issue by leocrawford** [neo4j-contrib/cypher-dsl#44]
The legal cypher query

```
collect(distinct("id"))
```

can't be written as

```
collect(distinct(identifier("id"))) 
```

without a cast to make it 

```
collect((ScalarExpression)distinct(identifier("id"))))
```

**Comment by michael-simons** [comment]
Hello @leocrawford we rebooted this project and the issue doesn't apply anymore in the new code base. Thanks for reporting, though.
