### ISSUE TITLE
multiple WhereClause are merged, but not WithClause  

### ISSUE THREAD

**Issue by leocrawford** [neo4j-contrib/cypher-dsl#45]
if we add multiple WhereClause to a Query the new additions are merged with the previous WhereClause to create a compound. This doesn't happen for WithClause which I can't determine any rationale behind. There may also be other clauses that could usefully be merged.

Suggestion for implementing is to change check in `Query.add` to use `instanceOf MergeClause` instead of `instanceof WhereClause` and create `MergeClause` with the single `merge` method. Happy to provide pull request if helpful

**Comment by michael-simons** [comment]
We have rebooted that project, @leocrawford. I think this issue doesn't apply anymore.

Maybe you want to check out the new implementation.

Thanks.
