### ISSUE TITLE
cypher-dsl for golang project

### ISSUE THREAD

**Issue by nistal97** [neo4j-contrib/cypher-dsl#469]
Greetings, is there an official dsl lib for golang projects like this one?

**Comment by michael-simons** [comment]
Hi. 
thanks for your patience. 
theres this https://github.com/manhcuongbk56/cypher-go-dsl

and this 
https://github.com/mindstand/go-cypherdsl

Neither one is from a Neo4j employee though. 

Paging @fbiville he is literally our Go (to) person for Go he might have opinions on that topic.

**Comment by michael-simons** [comment]
Gonna close this, this project is for Java. Thanks for having a look though, @nistal97
