### ISSUE TITLE
Upgrade to querydsl 4.0.x.

### ISSUE THREAD

**Issue by thomasdarimont** [neo4j-contrib/cypher-dsl#49]

**Comment by thomasdarimont** [comment]
hi @jexp,

thanks for the merge :) but I think you went to fast - I also updated the version in pom.xml: 
https://github.com/neo4j-contrib/cypher-dsl/blob/38c668ff3213c6f4ba3ad41ed4b3d7a9092b2b2d/pom.xml#L5
to have a dedicated version for the issue... alongside a proposed version upgrade.

I'd recommend to revise the pom again.

**Comment by thomasdarimont** [comment]
@jexp ping - did you see my comment?

**Comment by jexp** [comment]
It is fine in master, I changed the pom. It is currently built and deployed to: https://m2.neo4j.org/content/repositories/snapshots/org/neo4j/neo4j-cypher-dsl/

**Comment by thomasdarimont** [comment]
Cool! works fine - any plans for an official release?
I'm asking because this currently hinders Spring-Data-Neo4J to build :-(
https://jira.spring.io/browse/DATAGRAPH-793

**Comment by jexp** [comment]
@thomasdarimont did you see the work from @bradnussbaum?

https://build.spring.io/browse/SPRINGDATA-DATAGRAPH-1229
