### ISSUE TITLE
What is the license of this project?

### ISSUE THREAD

**Issue by szarnyasg** [neo4j-contrib/cypher-dsl#52]
The licensing of the project is not obvious for me:

* The [artifact in the Maven repository](http://mvnrepository.com/artifact/org.neo4j/neo4j-cypher-dsl) and the file headers suggest that the project is license under GPLv3.
* The [license file](https://github.com/neo4j-contrib/cypher-dsl/blob/3.0/LICENSE.txt) suggests an AGPLv3 license.
* There is a [license header file](https://github.com/neo4j-contrib/cypher-dsl/blob/3.0/asl-2-header.txt) for ASLv2.

As far as I can see, the project only uses Neo4j optionally or with a `test` scope, so in theory, it could be distributed under the Apache license. I believe the fluent API for building queries would be very useful for a lot of [openCypher](http://www.opencypher.org/) applications.

**Comment by jexp** [comment]
Sorry that was accidental. I copied the wrong license file :)
