### ISSUE TITLE
In version 5.0, distance replaced by point.distance

### ISSUE THREAD

**Issue by kmmuzahid** [neo4j-contrib/cypher-dsl#520]
It may be fixed for version 5 by simply changing the definition of the distance Function.
Possible solution->
```
	enum Spatials implements FunctionDefinition {

		POINT("point"),
		DISTANCE("point.distance");

		private final String implementationName;

		Spatials(String implementationName) {
			this.implementationName = implementationName;
		}

		@Override
		public String getImplementationName() {
			return implementationName;
		}
	}
```
```

**Comment by Andy2003** [comment]
Take a look at:

https://github.com/neo4j-contrib/cypher-dsl/blob/3e5e7d5fdae1c7394a59878890d22d3f8e96f51c/neo4j-cypher-dsl/src/test/java/org/neo4j/cypherdsl/core/DialectIT.java#L61-L66

to see how to use the new syntax

**Comment by michael-simons** [comment]
Thanks Andy.

Yes, this is already supported in our Dialect

https://github.com/neo4j-contrib/cypher-dsl/blob/main/neo4j-cypher-dsl/src/main/java/org/neo4j/cypherdsl/core/renderer/Dialect.java#L48

We use this in SDN6 already to keep up with the changes in Neo4j 5.

Thanks @Andy2003 for jumping in!
