### ISSUE TITLE
Missing `USE` clause capability

### ISSUE THREAD

**Issue by ikwattro** [neo4j-contrib/cypher-dsl#523]
I'm trying to use the Cypher DSL with composite databases, so far I don't find a way to perform a `USE` clause, like the following : 

```cypher
CALL {
  USE `shop.sales`
  MATCH (n:`Sale`) WHERE n.`transactionValue` > 500
  RETURN n
}
```

**Comment by michael-simons** [comment]
Tagged as a new feature, until available I would suggest building the inner queries separately and concatenate them.
