### ISSUE TITLE
`MATCH` after `UNWIND` not supported

### ISSUE THREAD

**Issue by ikwattro** [neo4j-contrib/cypher-dsl#524]
**Version 2022.8.1**

It seems that only returning or updating clauses are possible after an `UNWIND`, trying to migrate some of internal queries to cypher-dsl usage, starting with this very simple one : 

```cypher
UNWIND $ids AS id
MATCH (n:`Person`)
WHERE id(n) = id
RETURN n
```

**Comment by ikwattro** [comment]
It seems it can be fixed introducing an unnecessary `WITH` clause between the `UNWIND` and the `MATCH`, happy this issue being closed if it's by design.

**Comment by michael-simons** [comment]
That has been an oversight on my site. Thanks for spotting and reporting it!

For reference: https://s3.amazonaws.com/artifacts.opencypher.org/M21/railroad/SinglePartQuery.html

and for the writing ops I even implemented it that way.
