### ISSUE TITLE
[Question] How to use `COUNT {}` in returning clause

### ISSUE THREAD

**Issue by ikwattro** [neo4j-contrib/cypher-dsl#525]
**Version: 2022.8.1**

It's more of a question, if GH issues is not the right place please advise where to go ( please something else than Discord :) ).

Trying to produce the following query : 

```
MATCH (n) WHERE id(n) = $id
RETURN n, COUNT { (n)-[:ACTED_IN]->() } AS actedInDegreeOut
```

Usage of COUNT {} and EXISTS {} is a bit cryptic so far.

**Comment by michael-simons** [comment]
You can't build it right now, you will be able to parse it with 2023.0.0.
