### ISSUE TITLE
can't find any maven repository containing 3.0

### ISSUE THREAD

**Issue by unikzforce** [neo4j-contrib/cypher-dsl#53]

**Comment by unikzforce** [comment]
is there any release coming for 3.0?

**Comment by jexp** [comment]
Good point, I'll look into it next week.

**Comment by unikzforce** [comment]
Thank You very Much:)

**Comment by jexp** [comment]
Currently, I have little time to work on this, but we consider it.

**Comment by michael-simons** [comment]
Still needed or shall we close this?
