### ISSUE TITLE
Jackson: org.codehaus vs com.fasterxml

### ISSUE THREAD

**Issue by unikzforce** [neo4j-contrib/cypher-dsl#54]
is it possible to change all jackson references from codehaus to fasterxml namespace?

**Comment by unikzforce** [comment]
i'm currently using jhipster project and jhipster is using com.fasterxml which is very new and stable, but the 3.0 version of cypher-dsl , i thing it's one of the reasons i can't properly manually/locally add neo4j-cypher-dsl-3.0.jar to my gradle dependencies.

**Comment by unikzforce** [comment]
sorry my mistake! .. it's working finally:d but it would be very nice to  update jackson to latest com.fasterxml

**Comment by jexp** [comment]
Feel free to send in a pull request.

**Comment by michael-simons** [comment]
Hi @unikzforce. We are rebooting this project, the next version is actually dependency free, so you will have no issues with Jacksons.
