### ISSUE TITLE
Standalone procedure call with arguments as ResultStatement

### ISSUE THREAD

**Issue by zakjan** [neo4j-contrib/cypher-dsl#544]
The change from #490 is not available with arguments.

supported - `Cypher.call(procedureName).yield(Cypher.asterisk())`
not supported - `Cypher.call(procedureName).withArgs(...).yield(Cypher.asterisk())`

**Comment by michael-simons** [comment]
Indeed. Sorry for the oversight on my site as well.

**Comment by michael-simons** [comment]
Will be in 2022.8.3 and 2023.0.0, expect a release in the week from 23rd January the latest. Thanks for the report!
