### ISSUE TITLE
Implement Visitable.toString() with accept(prettyPrintingVisitor)

### ISSUE THREAD

**Issue by lukaseder** [neo4j-contrib/cypher-dsl#552]
Hi there! 👋

I've been looking into the possibility of making a SQL to Cypher transpiler (e.g. for https://www.jooq.org/translate). While debugging my way through this API, I notice that `Visitable::toString` tends not to be implemented. Would be useful in my opinion to implement it with `accept(prettyPrintingVisitor)`.

**Comment by michael-simons** [comment]
👋  Huhu. 

That's a cool idea, and we are happy to help you with that.

I honestly have issues combining `toString()` and the visitor concept in my head when reading your comment, sorry. Can you help with a small example?

**Comment by lukaseder** [comment]
Sure. E.g. from these examples:
https://neo4j-contrib.github.io/cypher-dsl/current/#properties

```java
System.out.println(Cypher.node("Person").named("p"));
System.out.println(personNode.relationshipTo(movieNode, "RATED").named("r"));
```

The output isn't helpful for debugging. Would be nice if this produced `p:Person` or `(p:`Person`)-[r:`RATED`]->(:`Movie`)`. I've had ton of great feedback for this simple feature in jOOQ. It's helpful not only for debugging but also for discovering the API, if a developer likes REPL style API discovery. Try something, `println`. Try something else, `println`. Currently, there are quite a few types that need to be known first before anything can be output. It's not impossible to do this explicitly with a `Renderer`, but it would be much more convenient via `toString()`.

There's already `Statement.getCypher()`, which does this, but only for `Statement`, not for arbitrary `Visitable`, which seems to be the top level type for your type hierarchy. But why not just implement the same thing in every type's `toString()`?

From a forward compatibility perspective, *what else* could `toString()` on these types possibly produce?

**Comment by michael-simons** [comment]
Ok, I find it useful myself…

```
[InternalNodeImpl{cypher=(m:Movie {title: 'The Matrix'})}]
Where{cypher=WHERE (m.releaseYear IS NOT NULL OR false)}
PropertyLookup{cypher=.releaseYear}
```
