### ISSUE TITLE
Apply covariant Collection overloads throughout the DSL

### ISSUE THREAD

**Issue by lukaseder** [neo4j-contrib/cypher-dsl#553]
The DSL tends to accept a `T...|Collection<T>` parameter type via overloads, which is convenient. For example:

```java
match(PatternElement...)
match(Collection<PatternElement>)
```

However, the `Collection<T>` overload is always (?) invariant, which is making it hard to create dynamic Cypher. Due to the invariance, I will have to keep upcasting things, e.g.:

```java
// Doesn't compile
Cypher.match(x.stream().map(t -> toNode(t)).toList());

// Compiles
Cypher.match(x.stream().map(t -> (PatternElement) toNode(t)).toList());
```

Despite `Node <: PatternElement`, I cannot pass a `List<Node>` to `match(Collection<PatternElement>)`. If, however, `match(Collection<? extends PatternElement>)` was there...

The problem doesn't appear with the varargs overload, because Java arrays are already covariant.

**Comment by michael-simons** [comment]
Nice seeing you here, Lukas! Good suggestion, thank you!

**Comment by lukaseder** [comment]
This wasn't included in version 2023.0.2 yet?

**Comment by michael-simons** [comment]
Nope, because breaking patch compatibility.

**Comment by lukaseder** [comment]
Ah, I see. I didn't realise your year based versioning is still semver capable.
