### ISSUE TITLE
Single DSL API entry point

### ISSUE THREAD

**Issue by lukaseder** [neo4j-contrib/cypher-dsl#573]
## Context:

One of jOOQ's greatest design decisions, IMO, is to put *everything* static in a single class namespace (`org.jooq.impl.DSL`), knowing that the only reason why there is even a class wrapper is because Java doesn't support package level functions, like e.g. kotlin or other languages. Personally, I think that was a mistake in early Java. A static method doesn't really need a class namespace.

The benefit of putting everything in a single class is discovery. Users never have to remember what namespace to look into for things. Also, namespaces don't have to be "evolved," because they're simply absent. What if a better name comes up? What if two names really are the same and should be refactored (e.g. `Conditions` and `Predicates`, see below)?

## Cypher DSL:

In cypher-dsl, there are multiple such entry points, e.g.:

- `Clauses`
- `Conditions`
- `Cypher` (where I first expected *everything* to be contained in)
  - It contains e.g. `literalXYZ()` or `parameter()` constructors, which I would have expected in `Literals` or `Parameters`
- `Expressions`
- `Functions`
- `Operations` (synonyms of virtual methods on `Expression`?)
- `Predicates` (how is it different from `Conditions`?)
- Perhaps others?

As mentioned before, I had to learn this and look up things using the IDE, hoping it would scan all the class candidates for possible static imports, making assumptions about method names. That's OK, it still works but:

- What if I don't know the method name, and would just like to *"discover"* options?
- What if I wanted to look at the structure view (IntellIJ) or outline view (Eclipse) to see *all* the options, alphabetically?

Eventually, a power user will learn the namespace, and it doesn't matter anymore. But for a beginner, I think the single namespace approach is more user friendly.

## Possible evolution:

I don't know if you agree with the above. If you don't, just reject this issue. If you do, you could place a delegate method in the `Cypher` class for every other expression/function constructor from the other classes, e.g.:

```java
public final class Cypher {
    public static @NotNull CountExpression count(PatternElement requiredPattern, PatternElement... patternElement) {
        return Expressions.count(requiredPattern, patternElement);
    }
}
```

Benefits:

- Implements the above expectations
- Backwards compatible

**Comment by michael-simons** [comment]
As you already realized, I'm torn… I started with Namespaces and on the way, I struggled myself. 

Not rejecting this, will think about it for a moment. Thanks a lot for the effort phrasing it out 👍

**Comment by Andy2003** [comment]
I can only agree with @lukaseder, as a user of the first hour I too often have the problem that I first search for a function in `Cypher` only to find that I have to search for it in one of the various other classes.

**Comment by michael-simons** [comment]
Thanks a ton for the effort and the good discussions, @Andy2003 🙇
