### ISSUE TITLE
[cypher-dsl-parser] Missing `MATCHED_PROPERTY` callback

### ISSUE THREAD

**Issue by ikwattro** [neo4j-contrib/cypher-dsl#574]
While there is the ability to provide callbacks for a lot of events, it seems there is none for knowing which property is matched against a particular node with label.

It seems the `matchClause()` method in the `CypherDslASTFactory` has already all the information available in the `where` argument but it is not passed to the 

```java
public Clause matchClause(InputPosition p, boolean optional, List<PatternElement> patternElements, InputPosition patternPos, List<Hint> hints, Where where) {
    var callbacks = this.options.getOnNewPatternElementCallbacks().getOrDefault(PatternElementCreatedEventType.ON_MATCH, List.of());
    return Clauses.match(optional, transformIfPossible(callbacks, patternElements), where, hints);
}
```

**Comment by michael-simons** [comment]
So two different things here:

```cypher
MATCH (m:Movie {title: 'The Matrix'}) WHERE m.releaseYear IS NOT NULL RETURN m
```

The pattern element you can already capture will contain the `title` property.
The where clause is unrelated to this and not necessarily connected to the pattern:

The above gives you

```
[InternalNodeImpl{cypher=(m:Movie {title: 'The Matrix'})}]
Where{cypher=WHERE (m.releaseYear IS NOT NULL OR false)}
```

**Comment by ikwattro** [comment]
@michael-simons I don't see how, the following callback 

```
UnaryOperator<PatternElement> nodesCollector = patternElement -> {
            patternElement.accept(segment -> {
                if (segment instanceof Node) {
                    Node node = (Node) segment;
                    node.getSymbolicName().map(SymbolicName::getValue).ifPresent(n -> nodes.put(n, node));
                }
            });
            return patternElement;
        };
```

And the following query 

```
var query = """
                MATCH (p:Person) WHERE p.email = $node.values.email
                MATCH (c:Certification) WHERE c.name="Neo4j Certified Professional"
                RETURN $id as id, exists((p)-[:HAS_CERTIFICATION]->(c)) as neoCertified
                """;
```

Always yield `null` for `properties`

**Comment by michael-simons** [comment]
Those properties / expressions are parsed why before being used in a Match clause. I tried a bunch of things that I thought might sense for you, but as I guess you would like to eventually rewrite the `MATCH` itself, I do now allow this.

You can just collection everything in the match factory now and do as you please, or shape the match like you want it. I added an example for the latter. I hope this helps.
