### ISSUE TITLE
Add a Predicates.exists(ResultStatement) overload

### ISSUE THREAD

**Issue by lukaseder** [neo4j-contrib/cypher-dsl#578]
Like SQL, Cypher supports `EXISTS()` with subqueries, see:
https://neo4j.com/docs/cypher-manual/current/syntax/expressions/#existential-subquery-with-where

Unless I'm misunderstanding some types from Cypher DSL, this doesn't yet have any representation in Cypher DSL?

**Comment by michael-simons** [comment]
Partially there as `org.neo4j.cypherdsl.core.StatementBuilder.ExposesExistentialSubqueryCall#asCondition`

**Comment by lukaseder** [comment]
I see, I can probably work with that for now.

**Comment by lukaseder** [comment]
Or, you try it :)

**Comment by zakjan** [comment]
This is an interesting case. Subqueries are useful for constructing Cypher from reusable building blocks.

I have methods returning `Statement`, for example `Statement getParent(Node startNode, Node parentNode)`, where `startNode` is input, `parentNode` is output.

`ExposesExistentialSubqueryCall#asCondition` works, but it causes that I would have to have two separate methods for the same subquery.

Is there a way to share the building blocks for both `CALL` and `EXISTS`?

**Comment by michael-simons** [comment]
@zakjan I hope the suggested implementation is what you are referring to. The same API will now be there for `count`, `exists`, `call`, however a bit scattered (see #573, but that is a different story).

**Comment by michael-simons** [comment]
Thanks, @zakjan much appreciated!
