### ISSUE TITLE
CypherParser incorrectly converts 'or' label matching condition to 'and' condition in parsed queries

### ISSUE THREAD

**Issue by bonelli** [neo4j-contrib/cypher-dsl#581]
I believe there is an issue with the CypherParser when parsing queries. A synthetic example to demonstrate the issue is provided below (the real-life query is more complex):

```
String statement = "MATCH (:`Human`|`Occupation`)-[:`OCCUPATION`*0..1]-(h:`Human`) RETURN h";
Statement parsed = CypherParser.parseStatement(statement);
parsed.getCypher(); // = "MATCH (:`Human`:`Occupation`)-[:`OCCUPATION`*0..1]-(h:`Human`) RETURN h"
```
The problem is that the query is parsed by replacing the matching options for labels from being in "or" condition on the labels to being in "and" condition for the labels. This is causing unexpected results as the intended matching condition is not being correctly applied.

**Comment by michael-simons** [comment]
Thanks a ton for opening this issue, @bonelli It is a weird thing between "this should not have been supported in the 1st case" and "I completely misunderstood the new parser methods…"

**Comment by bonelli** [comment]
You're welcome, thank you for all the good work.
I'm kinda in a hurry for a feature depending on this bugfix, so if you need some more details I'm really committed on this today.

Also if you can release a patch version with this fix as soon as it is ready I'd really appreciate, otherwise I'll use snapshot but I try never to depend on snapshots

**Comment by michael-simons** [comment]
https://github.com/neo4j-contrib/cypher-dsl/releases/tag/2023.0.2

Should be on central soonish.

**Comment by bonelli** [comment]
thank you
