### ISSUE TITLE
Re-render of identical expression tree should produce identical Cypher

### ISSUE THREAD

**Issue by lukaseder** [neo4j-contrib/cypher-dsl#585]
Currently, it seems that an "unnamed" `Node` created with `Cypher.node("x")` and embedded in `MATCH` produces arbitrarily generated aliases, e.g.

```
MATCH (guxtvIoA000:`person`) DELETE guxtvIoA000
MATCH (MEMrVzeE000:`person`) DELETE MEMrVzeE000
```

This makes writing tests based on such nodes hard. In my opinion, if the label is mandatory, then there are 2 possible algorithms:

- Make the label based on the node name, e.g. some hash value on `person`
- Enumerate labels as they appear in the query, e.g. `n1`

The hash value based approach is more robust and simpler to implement as the alias generation is context free. The same node instance will always be aliased the same way, no matter where it appears in the query. Of course, there can be conflicts, but that's what naming nodes is really for, no? To resolve such conflicts.

As an old Oracle guy, you probably remember cursor cache contention problems? In Oracle, this behaviour would have brought down production under load :)

Another argument in favour of my suggestion is that you claim `@Contact(pure = true)` everywhere, but this doesn't feel very "pure". (Sure, rendering doesn't have to be pure, but I still kinda expect it, at least between two consecutive runs, without changing configuration)

**Comment by lukaseder** [comment]
Just so I understand, why are these labels being generated at all? Is `MATCH (person) DELETE person` not valid Cypher?

**Comment by michael-simons** [comment]
* `@Contract(pure = true)` is not always correct, this I must fix… Shame on me
* In `(s:P)` `s` is an identifier that can be referenced later (aka [SymbolicName](https://s3.amazonaws.com/artifacts.opencypher.org/M21/railroad/SymbolicName.html)), the `P` is a [PatternElement](https://s3.amazonaws.com/artifacts.opencypher.org/M21/railroad/PatternElement.html). The pattern element used for matching, the symbolic name for reference.
* `MATCH (person) DELETE person` is valid Cypher and will delete all nodes (as long as they don't have relationships), not only nodes with `Person` label. Deleting only `Person` nodes is `MATCH (person:Person) DELETE person`.

I introduced the random generated identifiers to produce valid cypher when entities are referenced later in the stack.

You are correct though that it should not change for one statement. I'll see if I can fix this today.

**Comment by lukaseder** [comment]
> * `@Contract(pure = true)` is not always correct, this I must fix… Shame on me

Well, I guess you wanted to get IntelliJ's useful warnings that call sites should consume the output of a method call? Similar to `@CheckReturnValue`?

> * `MATCH (person) DELETE person` is valid Cypher and will delete all nodes (as long as they don't have relationships), not only nodes with `Person` label. Deleting only `Person` nodes is `MATCH (person:Person) DELETE person`.

Thanks for clarification. That makes sense. What I probably meant to say is `MATCH (:Person) DELETE ..`, though in that case, it's not possible to reference the unnamed `(:Person)` nodes? But in Cypher-DSL, it is, because we have a reference to the unnamed node, so a name can be generated (which you're doing already). So, the third suggestion (other than hash based or enumerated) would be to just use the node type, i.e. `person`?

**Comment by michael-simons** [comment]
Just using a variant of the nodes type is unpractical:  Nodes can have multiple types both for matching and DML (`(p:Person:Actor:Star)`… So that would at least require a bit more logic. Also I would probably need a generated value for anonymous nodes. Possible name class with something obvious like `person` might happen, too…

**Comment by lukaseder** [comment]
> Just using a variant of the nodes type is unpractical: Nodes can have multiple types both for matching and DML (`(p:Person:Actor:Star)`…

I see, they can have that pattern in Cypher-DSL, but probably not here in this translator. So that means we should generate things here (additionally).
