### ISSUE TITLE
Optional match with multiple where

### ISSUE THREAD

**Issue by igler** [neo4j-contrib/cypher-dsl#59]
Cannot construct the following query:
<code>MATCH (change:Change)-[codeRelation:CODE]-(code) WHERE id(code)=147 OPTIONAL MATCH (change)-[changeDetailsRelation:CHANGE_DETAILS]-(changeDetail) WHERE id(code)=147 RETURN change,codeRelation,changeDetailsRelation,changeDetail</code>
Cannot put a 2nd match-clause after the first where.

<pre><code>CypherQueryDSL
	.match(node("change").label("Change")
		.both("CODE").as("codeRelation")
		.node("code"))
	.where(id("code").eq(codeId))
	.match(node("change").label("Change") // not allowed after where
		.both("CHANGE_DETAILS").as("changeDetailsRelation")
		.node("changeDetail"))
	.where(id("code").eq(codeId))
	.returns(identifiers("change", "codeRelation", "changeDetailsRelation", "changeDetail"));</code></pre>

**Comment by michael-simons** [comment]
Thanks @igler for your interest. We are rebooting this project. With the upcoming version you'll be able to do the following:

Given the following imports

```java
import static org.assertj.core.api.Assertions.*;
import static org.neo4j.cypherdsl.Cypher.*;

import org.neo4j.cypherdsl.Cypher;
import org.neo4j.cypherdsl.renderer.Renderer;
```

Generate your query like this

```java
var change = node("Change").named("change");
var code = anyNode().named("code");
var codeRelation = change.relationshipBetween(code, "CODE").named("codeRelation");
var changeDetail = anyNode().named("changeDetail");
var changeDetailsRelation = change.relationshipBetween(changeDetail, "CHANGE_DETAILS").named("changeDetailsRelation");

var idIsEqualTo147 = code.internalId().isEqualTo(literalOf(147));
var statement = Cypher.match(codeRelation)
	.where(idIsEqualTo147)
	.optionalMatch(changeDetailsRelation)
	.where(idIsEqualTo147)
	.returning(change, codeRelation, changeDetailsRelation, changeDetail)
	.build();

assertThat(cypherRenderer.render(statement))
	.isEqualTo(
		"MATCH (change:`Change`)-[codeRelation:`CODE`]-(code) " 
		+ "WHERE id(code) = 147 " 
		+ "OPTIONAL MATCH (change)-[changeDetailsRelation:`CHANGE_DETAILS`]-(changeDetail) " 
		+ "WHERE id(code) = 147 RETURN change, codeRelation, changeDetailsRelation, changeDetail");
}
```
