### ISSUE TITLE
Predicate generation while having an string array over relation

### ISSUE THREAD

**Issue by msanadeem** [neo4j-contrib/cypher-dsl#60]
I have an string array over relation and unable to generate predicate with querydsl.

Consider the following scenario,

`NODE {id: 10} --- [LINKS_WITH {markets: ['US', 'France']}] ---> NODE {id: 21}`
`NODE {id: 10} --- [LINKS_WITH {markets: ['UK']}] ---> NODE {id: 22}`
`NODE {id: 10} --- [LINKS_WITH {markets: ['Canada']}] ---> NODE {id: 23}`
`NODE {id: 10} --- [LINKS_WITH {markets: ['Germany']}] ---> NODE {id: 24}`

Now I have to get all nodes associated with the node **having id 10** if the relation contains `France` in it.

I am unable to generate its predicate. Any help would be highly appreciated.

**Comment by michael-simons** [comment]
Thanks @msanadeem for your interest. We are rebooting this project. With the upcoming version you'll be able to do the following:

```java
var src = anyNode().withProperties("id", literalOf(10));
var n = anyNode().named("n");
var statement = Cypher.match(src.relationshipTo(n, "LINKS_WITH").named("r"))
	.where(literalOf("France").in(property("r", "markets")))
	.returning(n)
	.build();

assertThat(cypherRenderer.render(statement))
	.isEqualTo("MATCH ( {id: 10})-[r:`LINKS_WITH`]->(n) WHERE 'France' IN r.markets RETURN n");
```

Which gives to required cypher for your use case (`MATCH ( {id: 10})-[r:`LINKS_WITH`]->(n) WHERE 'France' IN r.markets RETURN n"`).
