### ISSUE TITLE
Add converter from Driver values to literals.

### ISSUE THREAD

**Issue by michael-simons** [neo4j-contrib/cypher-dsl#654]
Cc @loveleif

**Comment by loveleif** [comment]
Would be useful for Cypher Shell https://github.com/neo-technology/neo4j/blob/a2228408c89d2c8c3738777ee2ea0a231fc835be/public/community/cypher-shell/cypher-shell/src/main/java/org/neo4j/shell/parameter/ParameterPrettyRenderer.java#L62. For that use case we always want sorted maps though, so preferably make that configurable.
