### ISSUE TITLE
Renderer is marked as internal API, yet used in README example

### ISSUE THREAD

**Issue by ivangreene** [neo4j-contrib/cypher-dsl#66]
It's unclear whether it is appropriate for client code to use [`org.neo4j.cypherdsl.core.renderer.Renderer`](https://github.com/neo4j-contrib/cypher-dsl/blob/main/neo4j-cypher-dsl/src/main/java/org/neo4j/cypherdsl/core/renderer/Renderer.java#L31) directly, because it is annotated as an internal API, however it is shown being used in the README.md example

**Comment by michael-simons** [comment]
Yes, good catch. I'm gonna fix that.

It's safe to use https://github.com/neo4j-contrib/cypher-dsl/blob/main/neo4j-cypher-dsl/src/main/java/org/neo4j/cypherdsl/core/renderer/Renderer.java#L46, I'm gonna improve the docs.
