### ISSUE TITLE
Support Java's reactive Flow

### ISSUE THREAD

**Issue by israelstmz** [neo4j-contrib/cypher-dsl#699]
Neo4j Java driver now supports the 'Flow' based ReactiveSession. The cypher-dsl only supports the reactivestreams based ReactiveSession.

This causes a great deal of "adaptation" for applications using Java's Flow. Specifically, the new Mutiny 2 & Quarkus 3 are already based on Java's Flow.

It would be great to support this.

**Comment by michael-simons** [comment]
Oh that's nice feedback, @israelstmz So that means you are actually using our simplifications to execute queries?

**Comment by israelstmz** [comment]
Yes indeed. We were looking for a way to interact with neo4j from a quarkus application. The ogm did not give us enough control over the queries. Dealing with query strings is not clean and very error prone. Coming across this amazing DSL library was a shining star! This is such a great, easy, intuitive and clean approach for query building.

Thanks a lot for this!

**Comment by michael-simons** [comment]
Thank you so much for the kind words!!

So, for a stack agnostic version I would have to write subscribers, processors and publishers outside both Mutiny and Project Reactor. I am not only a bit reluctant here. 

If I don't write them myself, I would need to force either Project reactor onto you or Mutiny onto other people. 

Luckily, the executable statements of Cypher-DSL are not that much around the [driver](https://github.com/neo4j/neo4j-java-driver) which is automatically injected into Quarkus for you by our [extension](https://github.com/quarkiverse/quarkus-neo4j). 

I have written down some ways for you how to use a Cypher-DSL `Statement` with the drivers `ReactiveSession` and converting those publishers to Multis, Unis or keeping them:

```java
package io.quarkus.it.neo4j;

import java.util.concurrent.Flow;

import org.neo4j.cypherdsl.core.Cypher;
import org.neo4j.cypherdsl.core.Statement;
import org.neo4j.driver.Driver;
import org.neo4j.driver.Record;
import org.neo4j.driver.reactive.ReactiveResult;
import org.neo4j.driver.reactive.ReactiveSession;
import org.neo4j.driver.summary.ResultSummary;

import io.smallrye.mutiny.Multi;
import io.smallrye.mutiny.Uni;
import jakarta.inject.Inject;
import jakarta.ws.rs.Consumes;
import jakarta.ws.rs.GET;
import jakarta.ws.rs.Path;
import jakarta.ws.rs.Produces;
import jakarta.ws.rs.core.MediaType;

@Path("reactivefruits")
@Consumes(MediaType.APPLICATION_JSON)
public class ReactiveExample {

	@Inject
	Driver driver;

	static Uni<Void> sessionFinalizer(ReactiveSession session) { // <.>
		return Uni.createFrom().publisher(session.close());
	}

	@GET
	@Produces(MediaType.SERVER_SENT_EVENTS)
	public Multi<String> get() {

		var n = Cypher.node("Movie").named("n");
		var title = n.property("title");
		var statement = Cypher.match(n)
			.returning(title)
			.build();

		return Multi.createFrom()
			.publisher(fetchResults(statement))
			.map(record -> record.get(title.getName()).asString());
	}

	// Return Flow.Publisher or Multi according to your preferences, turning it back into a multi is a no-op with Multi.createFrom
	public final Flow.Publisher<Record> fetchResults(Statement statement) {

		return Multi.createFrom().resource(() -> driver.session(ReactiveSession.class),
				session -> session.executeRead(tx -> {
					var result = tx.run(statement.getCypher());
					return Multi.createFrom().publisher(result)
						.flatMap(ReactiveResult::records);
				}))
			.withFinalizer(ReactiveExample::sessionFinalizer);
	}


	// Example to execute without result
	public final Flow.Publisher<ResultSummary> execute(Statement statement) {
		return Multi.createFrom().resource(() -> driver.session(ReactiveSession.class),
				session -> session.executeRead(tx -> {
					var result = tx.run(statement.getCypher());
					return Multi.createFrom().publisher(result)
						.flatMap(ReactiveResult::consume);
				}))
			.withFinalizer(ReactiveExample::sessionFinalizer);
	}

	// Example to execute without result but returning uni (a unit is not a publisher)
	public final Uni<ResultSummary> executeAsUni(Statement statement) {

		return Uni.createFrom().publisher(Multi.createFrom().resource(() -> driver.session(ReactiveSession.class),
				session -> session.executeRead(tx -> {
					var result = tx.run(statement.getCypher());
					return Multi.createFrom().publisher(result)
						.flatMap(ReactiveResult::consume);
				}))
			.withFinalizer(ReactiveExample::sessionFinalizer));
	}
}
```

An other option would be going through the `AsyncSession` but that one has different semantics (here getting all the records asynchrony at once)

```java
@GET
	@Produces(MediaType.SERVER_SENT_EVENTS)
	public Multi<String> get() {

		var n = Cypher.node("Movie").named("n");
		var title = n.property("title");
		var statement = Cypher.match(n)
			.returning(title)
			.build();

		var session = driver.session(AsyncSession.class);
		return Multi.createFrom()
			.completionStage(ExecutableStatement.makeExecutable(statement)
				.fetchWith(session)
				.thenCompose(result -> session.closeAsync().thenApply(i -> result)))
			.flatMap(l -> Multi.createFrom().items(l.stream().map(record -> record.get(title.getName()).asString())));
	}
```

I would recommend following the first approach.

I think it's easier for you to add 2 or 3 helper method to a utility class for your service than doing this on the Cypher-DSL side of things. 

WDYT?

Paging @injectives for reference.

**Comment by israelstmz** [comment]
Hi and thanks very much for the elaborated suggestion. I see your points. I did see that a lot of copy-paste work was probably done over the driver's Session to support both 'Flow' and 'reactive streams' which is very user friendly on one hand but probably took a lot of annoying work.

considering your suggestions (voting for #1) I actually prefer the easy "adaptation" of the 'FlowAdapters'. So doing this:

``` java
var executableStatement = ReactiveExecutableStatement.of(statement);
var publisher = FlowAdapters.toFlowPublisher(
              driver.session(ReactiveSession.class, config)
                      .executeRead(executableStatement::fetchWith));
return Multi.createFrom().publisher(publisher)
              .map(record -> toResult(record));
```
does the job for now.

Thanks again.
BTW, I will love to hear any thoughts of how to safely & cleanly map a list of records to java objects... we can take it anywhere else of course.

**Comment by michael-simons** [comment]
My please, @israelstmz 

FWIW OGM does support all kind of wild custom queries, but alas, not in a reactive fashion. It's so good in that regard as it creates a local sub graph and then does the mapping. 

It depends on your definition of clean: Having something clean outside often implies doing the dirty work somewhere else (much as the annoying work mentioned above).

If you do a general purpose OGM such as Neo4j-OGM or Spring Data Neo4j you need to cater for all kind of eventualities, such as (not exhaustive)
- circular dependencies
- self references (aka back references)
- in combination with immutable objects (Java records, Kotlin data classes or something Lombok)

If you can eliminate some of those needs, I do think the driver records provide an easy way to extract their data into something proper. 

If the set of business domains isn't that big, I would probably just start with a set of mapper functions. 

Depending on the size of the service - or actually, in most any case - I would model very much after my use case, thinking in domain entities and map as I go (i.e. think `Order.of(driverRecord)` factories and then to the mapping their. I would try to stay away to create a class-graph-copy of the graph-database. It's a slippery slope… We see this quite often, actually, and I am not a fan (feels very much the same like taking relational and modelling all the tables 1:1 into JPA). Just because it seems easier with Graph, it does most likely not solve your actual business need.

**Comment by israelstmz** [comment]
much appreciated!

**Comment by michael-simons** [comment]
Closing this as there's little I can do from a point of this DSL.
