### ISSUE TITLE
Automatically generate symbolic name

### ISSUE THREAD

**Issue by ivangreene** [neo4j-contrib/cypher-dsl#70]
It would be convenient if there was an option or automatic feature to generate a random symbolic name, so that a node could be referred to multiple times in a query without needing to explicitly name it (i.e, reusing a variable of type Node)

```java
        Node strawberry = node("Fruit", mapOf("kind", literalOf("strawberry")));
        RENDERER.render(match(strawberry).set(strawberry.property("color").to(literalOf("red"))));
```

Right now, this will fail, because a SymbolicName needs to be added to 'strawberry' for it to be able to be referenced in the 'set' clause. Instead of setting the name that will never actually need to be referenced by the author, it could be automatically set to a random UUID or something else so that the variable of type Node can be reused throughout the query

**Comment by michael-simons** [comment]
Hi @ivangreene Thanks for your feedback.

This is a great idea and I think it will be very useful.
If you don't mind, feel free to have a look: https://github.com/neo4j-contrib/cypher-dsl/pull/74
