### ISSUE TITLE
Add `empty()` method to RelationshipChain

### ISSUE THREAD

**Issue by mvillafuertem** [neo4j-contrib/cypher-dsl#727]
Hi @michael-simons, 

just as there is an `empty()` static method to create the `Condition`. It would be great to have the analogous method for `RelationshipChain`

https://github.com/mvillafuertem/cypher-dsl/commit/cae1369dbd7d70f8b985113667cc5db9bf60903b

Thanks

**Comment by michael-simons** [comment]
Feel free to open this again with more insights about the use case. Thanks.
