### ISSUE TITLE
[feat] ability to extend Statement with limit clause

### ISSUE THREAD

**Issue by ikwattro** [neo4j-contrib/cypher-dsl#735]
Given I have already built a statement, it would be awesome to be able to extend the statement and add a `LIMIT` clause to it.

**Comment by michael-simons** [comment]
A statement can be so many things and there is not a clear spot in which cases adding a limit clause is semantically correct. 
Also, this is a slippery slope. Once I start making these things mutable, it won't like not stop here.
I would rather not add this.
