### ISSUE TITLE
[feat] support quantified path patterns

### ISSUE THREAD

**Issue by ikwattro** [neo4j-contrib/cypher-dsl#737]
In Neo4j 5.9, QPP is introduced, one of the main features is quantified path patterns ( among others :) ) https://neo4j.com/docs/cypher-manual/current/patterns/reference/#quantified-path-patterns

Eg: 

```
MATCH path=((x:A)-[:R]->(z:B WHERE z.h > 2)){1..3}
```

Potential cypher-dsl usage as for variable length relationships : 

```
Cypher.path().definedBy(...).min().max()
```

**Comment by michael-simons** [comment]
First I'm gonna update the parser being used (next week).
This feature: Not before summer break.

**Comment by ikwattro** [comment]
![image](https://github.com/neo4j-contrib/cypher-dsl/assets/1222009/d41ad1da-30c9-426c-9b8c-ee604c8468e9)

**Comment by michael-simons** [comment]
I sure do hope so. :D

**Comment by michael-simons** [comment]
FWIW I did not forget about this, but I do find it quite hard to come up with a good builder for those.

**Comment by zakjan** [comment]
The Cypher syntax is intimidating at the first glance, but I can imagine the usecases already :)

**Comment by subhradip-bose** [comment]
Any update on this?
