### ISSUE TITLE
[feat] provide direction when creating relationship

### ISSUE THREAD

**Issue by ikwattro** [neo4j-contrib/cypher-dsl#749]
In most of our scenarios, we build cypher-dsl statements programatically with runtime evolving schemas, meaning that the input to our cypher-dsl builder generally contains a triplet for relationships like `(nodeToExpand, otherNodeLabel, direction)` which leads to have very often the following logic in the cypher-dsl builder : 

```
var node = Cypher.node(nodeToExpand.label()).named("n");
var otherNode = Cypher.node(otherNodeLabel).named("o");
var rel = direction.equals(Direction.OUTGOING)
   ? node.relationshipTo(otherNode)
   : node.relationshipFrom(otherNode);
```

It would be great if as a user I could simply pass a direction, something like : 

```
node.relationshipTo(otherNode, "TYPE", Direction.INCOMING)
```

**Comment by michael-simons** [comment]
It's not like @jexp did request this already when we have been designing the builder ;)
