### ISSUE TITLE
'MERGE' clause should expose a 'REMOVE' operation

### ISSUE THREAD

**Issue by israelstmz** [neo4j-contrib/cypher-dsl#750]
In neo4j 5 (at least), a MERGE action allows the REMOVE operation. For example:

```cypher
MERGE (n:LABEL1)
REMOVE n:OLD_LABEL
SET n:NEW_LABEL;
```
yet, the dsl doesn't seem to support this. It does support the 'remove' operation but only on a MATCH clause.

**Comment by michael-simons** [comment]
Hi @israelstmz 

This is technically not part of the `MERGE` clause, but a new clause.
`SET` is only part of `MERGE` when defined through an action (https://s3.amazonaws.com/artifacts.opencypher.org/M22/railroad/Merge.html), which does not allow `REMOVE`, though.

But ofc, the merge builder should allow this to be build. On it.

**Comment by israelstmz** [comment]
Hay @michael-simons ,

That is huge! Thanks a lot. When is the next release ?

**Comment by michael-simons** [comment]
🙇‍♂️ thank you.

We can do next week.

**Comment by michael-simons** [comment]
2023.5.0 is out.
