### ISSUE TITLE
[feature] callback for function usage

### ISSUE THREAD

**Issue by ikwattro** [neo4j-contrib/cypher-dsl#776]
Hi Knight Rider of Flanders ! 

One of the beautiful things we could do with the cypher-dsl is to prevent the usage of the now deprecated `id()` function.

I couldn't find a way to intercept the usage with callbacks today, would love to see this implemented.

Cheers !

**Comment by michael-simons** [comment]
Hey why not using that feature over here? https://github.com/neo4j-contrib/cypher-dsl/commit/e9f6482d2795d313d7204ffcefa26720162e5c94

**Comment by michael-simons** [comment]
Correct link https://github.com/neo4j-contrib/cypher-dsl/blob/main/neo4j-cypher-dsl-parser/src/test/java/org/neo4j/cypherdsl/parser/CypherParserTest.java#L665

**Comment by ikwattro** [comment]
@michael-simons So `ON_CALL` is not only for procedure calls ?

**Comment by ikwattro** [comment]
Ok, I see in the release notes it's for Procedures and Functions ( I first thought about apoc functions :) ), will give it a spin now, thx m8

**Comment by ikwattro** [comment]
🤔 the only function invocation I get here is `MATCH`

```
var str = "MATCH (n) WHERE id(n) = $id RETURN n, {__id: id(n), __labels: labels(n)} AS __node__";
        var options = Options.newOptions()
                .withCallback(InvocationCreatedEventType.ON_INVOCATION, FunctionInvocation.class, e -> {
                    System.out.println(e.getFunctionName());
                    return e;
                })
                .build();
        CypherParser.parseExpression(str, options);
```

```
MATCH

Process finished with exit code 0
```

**Comment by michael-simons** [comment]
Because you are parsing only the first (parent) expression here. And it seems that the parser itself behaves … weird, wenn I ask it to parse match as an expression and not a clause. But this is a different (and actually not cypher-dsl's issue then…)

`CypherParser.parseExpression` vs `CypherParser.parseStatement`

**Comment by ikwattro** [comment]
Ah I'm stupid, old code from testing... It works <3

**Comment by ikwattro** [comment]
As usual, first class support, closing this as it fits all my needs

**Comment by michael-simons** [comment]
My pleasure. And fwiw, for once you'd been faster than closing this issue than me pushing a test that closes it.

Have a good week, Chris!

**Comment by ikwattro** [comment]
You're getting rusty 🤣 , likewise m8 !
