### ISSUE TITLE
[feat] Predicate isEmpty missing

### ISSUE THREAD

**Issue by JapuDCret** [neo4j-contrib/cypher-dsl#777]
Neo4j has the predicate function `isEmpty` (https://neo4j.com/docs/cypher-manual/current/functions/predicate/#functions-isempty)

But it is not implemented, see https://github.com/neo4j-contrib/cypher-dsl/blob/main/neo4j-cypher-dsl/src/main/java/org/neo4j/cypherdsl/core/Predicates.java

**Comment by michael-simons** [comment]
Thanks for the issue. Feature is added and will be included in the next release.
