### ISSUE TITLE
add CALL method to statement builder

### ISSUE THREAD

**Issue by sergeily** [neo4j-contrib/cypher-dsl#79]
It would be nice to add CALL method to statement builder.
functionality to call APOC and GDS methods

**Comment by michael-simons** [comment]
Hello @sergeily Thanks for reaching out.

I think that is already what you are looking for: https://github.com/neo4j-contrib/cypher-dsl/pull/65

For example:

https://github.com/neo4j-contrib/cypher-dsl/blob/main/neo4j-cypher-dsl/src/test/java/org/neo4j/cypherdsl/core/ProcedureCallsIT.java#L80-L89

It is not yet released but you might try out one of the build artifacts: https://github.com/neo4j-contrib/cypher-dsl/actions/runs/213438785

**Comment by sergeily** [comment]
Hello, @michael-simons 
Thanks for you answer.
Yes, this this actually that we are looking for

I'm sorry, we didn't notice that this is already implemented in the new version of cypher-dsl.

We currently use cypher-dsl 1.1.1 which does not have Cypher.call methods, so it's time to upgrade and try the new one.

Thank you again!

**Comment by michael-simons** [comment]
Thanks a lot for your feedback!

We will put out a release again this month…
See https://github.com/neo4j-contrib/cypher-dsl/releases

There are a couple of things I want to get into this, in addition to the procedure calls.
