### ISSUE TITLE
Includes All Operator Performs includes all Logic on wrong side of expression

### ISSUE THREAD

**Issue by jrsperry** [neo4j-contrib/cypher-dsl#813]
Cypher DSL Version: 2023.7.0 (experienced with earlier versions as well)

Sample Code: 

```
        var node = Cypher.node("Test").named("testNode");
        var builder = Cypher.match(node)
                .where(node.property("listProp").includesAll(Cypher.literalOf(List.of("string 1", "string 2"))))
                .returning(node);
        log.info(builder.build().getCypher());
```

Sample Data: 
`create (t:Test {listProp: ["string 1", "string 2", "string 3"]})`

The above code generates the following cypher: 
`MATCH (testNode:Test) WHERE all(x IN testNode.listProp WHERE x IN ['string 1', 'string 2']) RETURN testNode` which incorrectly checks if all node's listProp values are in the inputted list value and does not return the sample node (even though the sample node contains all the inputted values)

According to the documentation: 

```
	/**
	 * Creates a condition that checks whether this {@code expression} includes all elements of {@code rhs}.
	 *
	 * @param rhs The other collection to compare to, must evaluate into a list during runtime.
	 * @return A new condition
	 * @since 2022.7.0
	 */
	@NotNull @Contract(pure = true)
	default Condition includesAll(Expression rhs) {
		return Conditions.includesAll(this, rhs);
	}
```

It should be checking the node property list (lhs) contains all the values of the inputted list (rhs). The logic performed is backwards. 

The includesAny call has the same 'problem' although because it's an any the logic performed is accurate as it's looking only for commonalities between the lists, there may be edge cases with empty lists where the logic performed is bizarre and incorrect.

**Comment by jrsperry** [comment]
The Conditions.includesAll and includesAny just need to flip around the lhs and the rhs to get proper behavior. 

Old: 

```
	static Condition includesAll(Expression lhs, Expression rhs) {
		SymbolicName x = SymbolicName.of("x");
		return Predicates.all(x).in(lhs).where(x.in(rhs));
	}


	static Condition includesAny(Expression lhs, Expression rhs) {
		SymbolicName x = SymbolicName.of("x");
		return Predicates.any(x).in(lhs).where(x.in(rhs));
	}
```

Adjusted: 

```
	static Condition includesAll(Expression lhs, Expression rhs) {
		SymbolicName x = SymbolicName.of("x");
		return Predicates.all(x).in(rhs).where(x.in(lhs));
	}

	static Condition includesAny(Expression lhs, Expression rhs) {
		SymbolicName x = SymbolicName.of("x");
		return Predicates.any(x).in(rhs).where(x.in(lhs));
	}
```

I tried opening up a pull request but not authorized to push to the repo.

**Comment by michael-simons** [comment]
Thanks, @jrsperry for both the issue and the attempt to PR, much appreciated.

I'll have a look today.

WRT PR: Just fork the repo and create a PR in the future. Pushes to this repo are only for contributors and maintainers.

**Comment by michael-simons** [comment]
Introduced in #374 and I did oversee this. Sorry.

**Comment by jrsperry** [comment]
awesome.
