### ISSUE TITLE
calls to stored procedure

### ISSUE THREAD

**Issue by sergeily** [neo4j-contrib/cypher-dsl#82]
It's not possible to use statement builder's methods
org.neo4j.cypherdsl.core.Cypher#call + org.neo4j.cypherdsl.core.ExposesCall.ExposesWithArgs#withArgs

because "call" returns package-private interface org.neo4j.cypherdsl.core.ProcedureCall.OngoingStandaloneCallWithoutArguments

Example:
```
        Statement call = Cypher
                .call("dbms.listConfig")
                .withArgs(Cypher.literalOf("browser"))
                .yield("name")
                .build();
```

P.S.
Test org.neo4j.cypherdsl.core.ProcedureCallsIT#withArgsAndYield passes because of the same package

PPS
May be possible to use something like
org.neo4j.cypherdsl.core.StatementBuilder.OngoingReadingWithoutWhere as return to continue the builder chain ?

**Comment by michael-simons** [comment]
Very good catch! Haven't noticed when writing the tests. Gonna fix this ASAP.
