### ISSUE TITLE
[feat] Support pattern WHERE clauses

### ISSUE THREAD

**Issue by zakjan** [neo4j-contrib/cypher-dsl#858]
Hi, it seems DSL is missing support for pattern WHERE clauses.

For both [nodes](https://neo4j.com/docs/cypher-manual/current/patterns/reference/#node-patterns-examples) and [relationships](https://neo4j.com/docs/cypher-manual/current/patterns/reference/#relationship-patterns-examples):

- `(n WHERE n.departs > time() + duration('PT30M'))`
- `()-[r WHERE 10 < r.distance < 100]->()`

This should likely come before https://github.com/neo4j-contrib/cypher-dsl/issues/737, because QPP allows them as well. It might be necessary to have them already before starting on QPP.

**Comment by michael-simons** [comment]
Funny thing, I just started to work on this early today… Exactly for #737

**Comment by zakjan** [comment]
Good news, thanks 😄

**Comment by zakjan** [comment]
I'll test it on our side when it's released.

One question, why `where(Expression predicate)` accepts `Expression` instead of `Condition`?
