### ISSUE TITLE
Add support for temporal functions

### ISSUE THREAD

**Issue by RamonLM** [neo4j-contrib/cypher-dsl#89]
Support for the following temporal functions supported by Neo4j:
- date()
- datetime()
- localdatetime()
- localtime()
- time()

Reference: https://neo4j.com/docs/cypher-manual/current/functions/temporal/

**Comment by michael-simons** [comment]
Thanks @RamonLM See #92. Would that work for your usecase? Cheers, Michael.

**Comment by RamonLM** [comment]
Thank you, this is great.
