### ISSUE TITLE
cannot generate static model relationships with extensible nodes

### ISSUE THREAD

**Issue by mb-nick** [neo4j-contrib/cypher-dsl#970]
Hi, 

I want to generate a static model with cypher-dsl-codegen-core. I have relationships that include extensible nodes. The generated code is not compilable because of issues with the generics definitions.

I used version 2023.9.6.

Here is a code snippet to generate non-compilable code.
```
var targetDir = Path.of("target/generated-sources/");
var configuration = Configuration.newConfig().withDefaultPackage("org.example").build();
var foo = NodeModelBuilder.create(configuration, null, "Foo")
        .setExtensible(true)
        .addLabel("Foo")
        .addProperty("prop1");
var bar = NodeModelBuilder.create(configuration, null, "Bar")
        .addLabel("Bar")
        .addProperty("prop2");
var relation = RelationshipModelBuilder.create(configuration, null, "Related")
        .addRelationship(foo, bar);

foo.writeTo(targetDir);
bar.writeTo(targetDir);
relation.writeTo(targetDir);
```

**Comment by michael-simons** [comment]
@Andy2003 care to have a look? I think u worked in that area the last time.

**Comment by michael-simons** [comment]
Hey @mb-nick Can you try if this https://github.com/neo4j-contrib/cypher-dsl/pull/974 works for you?

You'll get a build with `./mvnw -Dfast package` (JDK17 required).

The extensible thing is really not my area of expertise and has been brought in by @Andy2003 for a thing he was building. While the SDN code generate uses the builders too, it does not use the extension feature. I am kinda hoping here I don't break potential other users too much, but I needed to fix the generated classes for the nodes first, than moved on to the relation.

**Comment by Andy2003** [comment]
Lgtm, thank you for fixing it!
